backend:
  name: git-gateway
  repo: kaina-agency/macc-cookbook
  branch: master
local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Link",
          name: "url",
          widget: "string",
          required: false,
          hint: "Is this a recipe you found online? You can share it here with your notes and modifications.",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Recipe & Notes", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { name: "author", widget: "hidden" }
